on:
  workflow_dispatch:
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:

name: Tests/Release
jobs:
  # Build & test simple source release before wasting hours building and
  # testing the binary build matrix.
  sdist:
    name: Creating source release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setting up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: "false"

      - name: Building source distribution
        run: |
          uv build --sdist

      - name: Ensuring documentation builds
        run: |
          cd docs && uv run make clean html

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: dist-sdist
          path: dist/*.tar.gz
  
  build_wheels:
    needs: [sdist]
    name: "[${{ strategy.job-index }}/${{ strategy.job-total }}] py${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
        py: ["cp39", "cp310", "cp311", "cp312", "cp313", "cp314"]

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setting up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: "false"

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3.7.0
        with:
          platforms: all

      - name: Build & test wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_BUILD: "${{ matrix.py }}-*"

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: dist-${{ matrix.os }}-${{ matrix.py }}
          path: ./wheelhouse/*.whl

  upload_all:
    name: Uploading built packages to pypi for release.
    needs: [build_wheels, sdist]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v7.0.0
      with:
        pattern: dist-*
        merge-multiple: true
        path: dist

    - name: Installing uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.13"
        enable-cache: "false"

    - name: Publishing to PyPI
      run: uv publish dist/*

  build_documentation:
    name: Building & uploading documentation.
    needs: [upload_all]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setting up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: "false"

      - name: Installing release dependencies.
        run: |
          uv sync

      - name: Building documentation
        run: |
          cd docs && uv run make clean html

      - name: Publishing documentation
        run: |
          uv run ghp-import -f -n -c pysimdjson.tkte.ch -p docs/_build/html
